-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fullstackchallenge_db
-- -----------------------------------------------------

USE `fullstackchallenge_db` ;

-- -----------------------------------------------------
-- Table `fullstackchallenge_db`.`TB_HIERARCHY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstackchallenge_db`.`TB_HIERARCHY` (
  `HIERARCHY_ID` BIGINT AUTO_INCREMENT NOT NULL,
  `LEVEL` INT NOT NULL,
  `OFFICE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`HIERARCHY_ID`))
ENGINE = InnoDB;

INSERT INTO `fullstackchallenge_db`.`TB_HIERARCHY`(HIERARCHY_ID, LEVEL, OFFICE) VALUES(1, 5, 'Presidência');
INSERT INTO `fullstackchallenge_db`.`TB_HIERARCHY`(HIERARCHY_ID, LEVEL, OFFICE) VALUES(2, 4, 'Gerência');
INSERT INTO `fullstackchallenge_db`.`TB_HIERARCHY`(HIERARCHY_ID, LEVEL, OFFICE) VALUES(3, 3, 'Analista');
INSERT INTO `fullstackchallenge_db`.`TB_HIERARCHY`(HIERARCHY_ID, LEVEL, OFFICE) VALUES(4, 2, 'Desenvolvimento');
INSERT INTO `fullstackchallenge_db`.`TB_HIERARCHY`(HIERARCHY_ID, LEVEL, OFFICE) VALUES(5, 1, 'Estágiário/Trainee');


-- -----------------------------------------------------
-- Table `fullstackchallenge_db`.`TB_EMPLOYEE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstackchallenge_db`.`TB_EMPLOYEE` (
  `EMPLOYEE_ID` BIGINT AUTO_INCREMENT NOT NULL,
  `NAME` VARCHAR(100) NOT NULL,
  `PASSWORD` TEXT NOT NULL,
  `IMAGE` LONGTEXT NULL,
  `SCORE` INT NOT NULL,
  `PASSWORD_LEVEL` VARCHAR(45) NOT NULL,
  `HIERARCHY_ID` BIGINT NOT NULL,
  `SUPERIOR_EMPLOYEE_ID` BIGINT NOT NULL,
  PRIMARY KEY (`EMPLOYEE_ID`, `HIERARCHY_ID`),
  INDEX `fk_TB_EMPLOYEE_TB_HIERARCHY1_idx` (`HIERARCHY_ID` ASC),
  CONSTRAINT `fk_TB_EMPLOYEE_TB_HIERARCHY1`
    FOREIGN KEY (`HIERARCHY_ID`)
    REFERENCES `fullstackchallenge_db`.`TB_HIERARCHY` (`HIERARCHY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `fullstackchallenge_db`.`TB_EMPLOYEE`(EMPLOYEE_ID, NAME, PASSWORD, SCORE, PASSWORD_LEVEL, HIERARCHY_ID, SUPERIOR_EMPLOYEE_ID)
VALUES(1, 'Steve Jobs', 'FAs4a$G¨Dafsfs&&&*nsamdksnd', 76, 'BOM', 1, 1);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
